blank_issues_enabled: false
contact_links:
  - name: Rust Implementation Issue
    url: https://github.com/twardoch/uubed-rs/issues/new
    about: Report issues specific to the Rust core implementation
  - name: Python API Issue
    url: https://github.com/twardoch/uubed-py/issues/new
    about: Report issues with the Python bindings or API
  - name: Documentation Issue
    url: https://github.com/twardoch/uubed-docs/issues/new
    about: Report documentation errors or suggest improvements
  - name: General Discussion
    url: https://github.com/twardoch/uubed/discussions
    about: Ask questions and discuss ideas with the community