[build-system]
requires = ["maturin>=1.7,<2"]
build-backend = "maturin"

[project]
name = "uubed"
version = "0.1.0"
requires-python = ">=3.10"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "uubed._native"
python-source = "../src"
develop = true