labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for starting a discussion! Please provide as much detail as possible to help the community assist you.

  - type: dropdown
    id: discussion-type
    attributes:
      label: Discussion Type
      description: What type of discussion is this?
      options:
        - General Question
        - Feature Request
        - Performance Discussion
        - Integration Help
        - Best Practices
        - Research Ideas
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this discussion relate to?
      options:
        - General (cross-cutting)
        - uubed-rs (Rust implementation)
        - uubed-py (Python bindings)
        - uubed-docs (Documentation)
        - Not sure
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your question, idea, or topic of discussion
      placeholder: Please provide details about what you'd like to discuss...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context, code examples, or related information
      placeholder: |
        - Code examples
        - Use case details
        - Performance requirements
        - Integration constraints
        - Related research or resources

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: System and version information
      placeholder: |
        - OS: 
        - Python version:
        - uubed version:
        - Hardware specs: