labels: ["integration", "help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        ## Integration Discussion
        
        Get help integrating uubed with your application, framework, or vector database.

  - type: dropdown
    id: integration-target
    attributes:
      label: Integration Target
      description: What are you trying to integrate uubed with?
      options:
        - Vector Database (Pinecone, Weaviate, Qdrant, etc.)
        - Search Engine (Elasticsearch, OpenSearch, etc.)
        - ML Framework (LangChain, Llama Index, etc.)
        - Web Application
        - Data Pipeline
        - Other Library/Framework
        - Custom Application
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case Description
      description: Describe what you're trying to achieve
      placeholder: |
        - What type of embeddings are you working with?
        - What is your search/retrieval workflow?
        - What encoding method are you considering?
        - What are your performance requirements?
        - What constraints do you have (storage, latency, etc.)?
    validations:
      required: true

  - type: textarea
    id: current-approach
    attributes:
      label: Current Approach
      description: What have you tried so far?
      placeholder: |
        - Current embedding storage method
        - Code snippets you've tried
        - Integration attempts
        - Issues you've encountered

  - type: textarea
    id: specific-questions
    attributes:
      label: Specific Questions
      description: What specific help do you need?
      placeholder: |
        - Technical questions about implementation
        - Best practices for your use case
        - Performance optimization advice
        - Architecture recommendations
        - Code review requests

  - type: textarea
    id: environment
    attributes:
      label: Technical Environment
      description: Your technical stack and constraints
      placeholder: |
        - Programming language(s):
        - Framework/platform:
        - Vector database/search engine:
        - Scale (number of embeddings, QPS, etc.):
        - Infrastructure (cloud, on-premise, etc.):