labels: ["performance"]
body:
  - type: markdown
    attributes:
      value: |
        ## Performance Discussion
        
        Share performance results, optimizations, or questions about uubed's performance characteristics.

  - type: dropdown
    id: performance-topic
    attributes:
      label: Performance Topic
      description: What aspect of performance are you discussing?
      options:
        - Benchmarking Results
        - Performance Issues
        - Optimization Ideas
        - Comparison with Other Libraries
        - Hardware-Specific Performance
        - Memory Usage
        - Scaling Characteristics
    validations:
      required: true

  - type: textarea
    id: benchmark-results
    attributes:
      label: Benchmark Results or Performance Data
      description: Share your performance measurements, benchmark results, or profiling data
      placeholder: |
        Please include:
        - Encoding method (Eq64, Shq64, T8q64, Zoq64)
        - Input size and characteristics
        - Hardware specifications
        - Timing results or throughput numbers
        - Memory usage measurements
        
        Example:
        Method: Eq64
        Input: 1000 embeddings, 1024 bytes each
        Hardware: Apple M1 Pro, 16GB RAM
        Results: 45ms total, 234 MB/s throughput

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: System specifications and configuration
      placeholder: |
        - OS and version:
        - CPU:
        - RAM:
        - Python version:
        - Rust version (if applicable):
        - uubed version:
        - Compilation flags (if built from source):
    validations:
      required: true

  - type: textarea
    id: comparison
    attributes:
      label: Comparison or Context
      description: How does this compare to other libraries, previous versions, or expected performance?
      placeholder: |
        - Comparison with other encoding libraries
        - Performance vs previous uubed versions  
        - Expected vs actual performance
        - Performance goals or requirements

  - type: textarea
    id: questions
    attributes:
      label: Questions or Discussion Points
      description: What would you like to discuss about these performance characteristics?
      placeholder: |
        - Questions about the results
        - Ideas for optimization
        - Unexpected behavior
        - Requests for guidance