name: Nightly Benchmarks

on:
  schedule:
    # Run at 2 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  benchmark-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Rust benchmarks
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'uubed-rs',
              workflow_id: 'benchmarks.yml',
              ref: 'main'
            });

  benchmark-python:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Python benchmarks
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'uubed-py',
              workflow_id: 'benchmarks.yml',
              ref: 'main'
            });

  collect-results:
    needs: [benchmark-rust, benchmark-python]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for benchmarks to complete
        run: sleep 300  # Wait 5 minutes for benchmarks

      - name: Create benchmark summary
        run: |
          echo "# Nightly Benchmark Summary - $(date)" > benchmark-summary.md
          echo "" >> benchmark-summary.md
          echo "## Performance Metrics" >> benchmark-summary.md
          echo "" >> benchmark-summary.md
          echo "Check individual repositories for detailed benchmark results:" >> benchmark-summary.md
          echo "- [Rust Benchmarks](https://github.com/${{ github.repository_owner }}/uubed-rs/actions)" >> benchmark-summary.md
          echo "- [Python Benchmarks](https://github.com/${{ github.repository_owner }}/uubed-py/actions)" >> benchmark-summary.md

      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-summary
          path: benchmark-summary.md